name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff

      - name: Ruff (non-blocking)
        run: ruff check --exit-zero .

      - name: Import + /healthz smoke
        run: |
          python - <<'PY'
          import importlib
          rag_api = importlib.import_module('rag_api')
          app = rag_api.app
          c = app.test_client()
          r = c.get('/healthz')
          assert r.status_code == 200, r.data
          print('✅ /healthz:', r.get_json())
          PY

      - name: Pytest
        run: pytest -q
